- name: add pgp key
  apt_key: url=https://packagecloud.io/gpg.key
  
- name: add repo
  apt_repository: repo='deb https://packagecloud.io/grafana/stable/debian/ wheezy main' state=present update_cache=yes

- name: install grafana
  apt: name=grafana

- name: start and autostart grafana-server
  service: name=grafana-server state=started enabled=yes

- name: change http_port if required
  ini_file: dest=/etc/grafana/grafana.ini
            section=server
            option=http_port
            value={{ grafana_http_port }}
            backup=yes
  notify: restart grafana-server