---
- name: get grafana version
  uri:
    url: "http://{{ grafana_http_addr }}:{{ grafana_http_port }}/login"
    return_content: yes
  register: grafana

- set_fact:
    grafana_info: "{{ grafana|regex_replace('.*window\\.grafanaBootData\\s*=\\s*({.*});.*', '\\1')|replace('\\t','')|replace('\\n','')|regex_replace('(\\w+)(' + ':' + '\\s*(\\{|\\[))','\"\\1\"\\2') }}"

- name: show versions
  debug: msg="current vesrion {{ grafana_info.settings.buildInfo.version }}, expected version {{ grafana_install_version }}"

- fail: msg="version check failed"
  when: grafana_info.settings.buildInfo.version|version_compare(grafana_install_version, '!=')
